name: GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node 17
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Install
      run: npm install
    - name: Build and Deploy
      env:
        NODE_ENV: production
        CI: false
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
          CI=false
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/mustiikhalil/mmk-website.git
          npm run build
          cp -R assets build/
          npm run deploy

